// <auto-generated />
namespace ClothBazar.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newWeb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newWeb1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104030753331_newWeb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
